[env:teensy41_sine]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    https://github.com/tonton81/FlexCAN_T4.git
    https://github.com/odriverobotics/ODriveArduino.git
build_src_filter = +<teensy_SineWaveCAN.cpp>
monitor_port = COM17
monitor_speed = 115200

[env:teensy41_sine_original]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    https://github.com/tonton81/FlexCAN_T4.git
    https://github.com/odriverobotics/ODriveArduino.git
build_src_filter = +<teensy_SineWaveCAN_original.cpp>
monitor_port = COM17

[env:teensy41_tester]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    https://github.com/tonton81/FlexCAN_T4.git
build_src_filter = +<teensy_TeensyCANtester.cpp>
monitor_port = COM17

[env:teensy41_middleman]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    https://github.com/tonton81/FlexCAN_T4.git
    https://github.com/odriverobotics/ODriveArduino.git
build_src_filter = +<teensy_middleman.cpp>
monitor_port = COM17
monitor_speed = 115200